"""
Loss Utility Functions
=========================

This module contains utilities for 
"""
import torch
import torch.nn as nn

class NormalizedRMSELoss(nn.Module):
    def __init__(self, eps=1e-8, reduction='none'):
        """
        Normalized Root Mean Squared Error (NRMSE) Loss.
        Computes the continuous-time integral loss approximation: sqrt(MSE / Var(y_true))
        """
        super().__init__()
        self.eps = eps
        self.reduction = reduction

    def forward(self, y_pred, y_true):
        # y_pred and y_true shapes: [Batch, Seq_Len, Dim]
        
        # 1. Compute element-wise squared error
        squared_error = (y_true - y_pred) ** 2
        
        # 2. Compute Mean Squared Error (MSE) across the sequence dimension
        # Keep dims to allow proper broadcasting if needed
        mse = torch.mean(squared_error, dim=1, keepdim=True) # [Batch, 1, Dim]
        
        # 3. Compute variance of the true target signal along the sequence
        # We add a small epsilon to prevent division by zero for flat targets
        var_true = torch.var(y_true, dim=1, keepdim=True, unbiased=True) + self.eps # [Batch, 1, Dim]
        
        # 4. Compute the normalized loss per sequence and channel
        loss = torch.sqrt(mse / var_true) # [Batch, 1, Dim]
        
        # Match dimensions to [Batch, Seq_Len, Dim] by broadcasting back across time steps
        loss = loss.expand_as(y_true)
        
        if self.reduction == 'mean':
            return loss.mean()
        elif self.reduction == 'sum':
            return loss.sum()
        return loss # returns 'none' (shape: [Batch, Seq_Len, Dim]) for channel-wise tracking
    
    
#=== FUNCTION FOR BOUNDED RELATIVE LOSS ===#
def bounded_relative_loss(pred, target, eps=1e-6):
    """
    Computes a symmetric relative error loss bounded strictly between 0 and 1.

    Parameters:
    - pred (torch.Tensor): The predicted values tensor generated by the controller model.
    - target (torch.Tensor): The ground-truth target values tensor (the training signals).
    - eps (float): A tiny stabilization constant to prevent division-by-zero errors (default: 1e-6).

    Returns:
    - loss (torch.Tensor): A scalar tensor representing the mean bounded relative error across all elements.

    The function evaluates error contextually by dividing the absolute difference of the vectors by 
    the combined absolute magnitudes of both the prediction and target values. This normalization 
    constrains every single element-wise error valuation strictly within a [0.0, 1.0] interval, 
    making it scale-invariant and ideal for systems with wide operating setpoint changes.
    """
    # Calculate absolute element-wise differences
    abs_diff = torch.abs(pred - target)
    
    # Scale denominator by combined absolute magnitudes to guarantee a hard ceiling at 1.0
    denominator = torch.abs(target) + torch.abs(pred) + eps
    
    # Compute element-wise relative loss inside [0, 1]
    relative_loss = abs_diff / denominator
    
    # Return the scalar mean loss across the entire tensor batch
    return torch.mean(relative_loss)
    

def msle_loss(pred, target):
    """
    Mean Squared Logarithmic Error (MSLE).
    Applies logarithmic scaling to continuous values to handle tight ranges 
    and heavily penalizes underestimations.
    """
    # Adding 1.0 ensures the value inside the log is always >= 1.0, 
    # since log(1) = 0. This prevents negative loss values.
    log_pred = torch.log(pred + 1.0)
    log_target = torch.log(target + 1.0)
    
    return torch.mean((log_pred - log_target) ** 2)

def relative_huber_loss(u_pred, u_truth, delta=0.1):
    """
    Relative Huber loss for control signals.
    Args:
        u_pred: Predicted control sequence (torch.Tensor)
        u_truth: Ground truth control sequence (torch.Tensor)
        delta: Threshold for Huber loss (default: 0.1)
    Returns:
        loss: Scalar tensor
    """
    error = (u_pred - u_truth) / (u_truth.abs())  # Normalize by u_truth magnitude
    huber_loss = torch.where(
        torch.abs(error) < delta,
        0.5 * error ** 2,
        delta * (torch.abs(error) - 0.5 * delta)
    )
    return torch.mean(huber_loss)

def mape_loss(u_pred, u_truth):
    """
    Penalizes the percentage difference. 
    Useful if u values span different orders of magnitude.
    """
    error = (u_pred - u_truth).abs() / (u_truth.abs() + 1e-8)
    return torch.mean(error)


def sobolev_loss(u_pred, u_truth, alpha=0.5):
    """
    Combines MSE with a penalty on the difference in derivatives.
    alpha: weighting factor for the derivative penalty.
    """
    # Standard MSE
    mse = torch.mean((u_pred - u_truth)**2)
    
    # Calculate derivatives along the time dimension (dim=1)
    # Assumes shape [batch, seq_len, features]
    du_pred = u_pred[:, 1:, :] - u_pred[:, :-1, :]
    du_truth = u_truth[:, 1:, :] - u_truth[:, :-1, :]
    
    deriv_loss = torch.mean((du_pred - du_truth)**2)
    
    return mse + alpha * deriv_loss


def log_cosh_loss(u_pred, u_truth):
    """
    A smooth approximation of Huber loss that is easier to optimize 
    with second-order methods.
    """
    error = u_pred - u_truth
    return torch.mean(torch.log(torch.cosh(error + 1e-12)))


def cosine_shape_loss(u_pred, u_truth):
    """
    Focuses on the shape/alignment of the curves.
    Returns 1 - similarity (so 0 is perfect alignment).
    """
    cos = torch.nn.CosineSimilarity(dim=1) # Across the time dimension
    # Flattening to [batch, seq_len * features]
    sim = cos(u_pred.flatten(1), u_truth.flatten(1))
    return 1.0 - torch.mean(sim)


def hybrid_control_loss(u_pred, u_truth):
    # 1. Accuracy (Huber)
    l1 = torch.nn.functional.huber_loss(u_pred, u_truth, delta=0.5)
    
    # 2. Smoothness (Derivative)
    du_pred = u_pred[:, 1:, :] - u_pred[:, :-1, :]
    du_truth = u_truth[:, 1:, :] - u_truth[:, :-1, :]
    l2 = torch.mean((du_pred - du_truth)**2)
    
    # 3. Shape (Cosine)
    l3 = cosine_shape_loss(u_pred, u_truth)
    
    return l1 + 0.5 * l2 + 0.1 * l3